-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE POLICY "Allow users to see their own and invited team details"
    ON public.team
    AS PERMISSIVE
    FOR SELECT
    TO public
    USING (((auth.uid() IN ( SELECT user_team.user_id
   FROM user_team
  WHERE (user_team.team_id = team.id))) OR (auth.uid() IN ( SELECT team_invite.invitee_id
   FROM team_invite
  WHERE (team_invite.team_id = team.id)))));

DROP POLICY IF EXISTS "Team members can view their own team details." ON public.team;
