-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.team_invite
    ADD COLUMN team_id uuid NOT NULL;
ALTER TABLE IF EXISTS public.team_invite DROP CONSTRAINT IF EXISTS team_invite_pkey;

ALTER TABLE IF EXISTS public.team_invite
    ADD CONSTRAINT team_invite_pkey PRIMARY KEY (inviter_id, invitee_id, team_id);

ALTER TABLE IF EXISTS public.team_invite
    ADD CONSTRAINT team_invite_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.team (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
